package com.badlogic.gdx.backends.webgpu.webgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPUCompositeAlphaMode {
    Auto,
    Opaque,
    Premultiplied,
    Unpremultiplied,
    Inherit,
}