package com.badlogic.gdx.backends.webgpu.webgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPUBufferBindingType {
    Undefined,
    Uniform,
    Storage,
    ReadOnlyStorage,
}