package com.badlogic.gdx.backends.webgpu.webgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
import jnr.ffi.Pointer;
import jnr.ffi.annotations.Delegate;

public interface WGPUCompilationInfoCallback {

	@Delegate
	void invoke(WGPUCompilationInfoRequestStatus status, WGPUCompilationInfo compilationInfo, Pointer userdata);
}
