
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUHeapProperty {
	public static final int Undefined = 0x0;
	public static final int DeviceLocal = 0x1;
	public static final int HostVisible = 0x2;
	public static final int HostCoherent = 0x4;
	public static final int HostUncached = 0x8;
	public static final int HostCached = 0x10;
}
