
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPURequestDeviceCallbackInfo2 extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
	private final Enum<WGPUCallbackMode> mode = new Enum<>(WGPUCallbackMode.class);
	private final Pointer callback = new Pointer();
	private final Pointer userdata1 = new Pointer();
	private final Pointer userdata2 = new Pointer();

	private WGPURequestDeviceCallbackInfo2 () {
	}

	@Deprecated
	public WGPURequestDeviceCallbackInfo2 (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPURequestDeviceCallbackInfo2 createHeap () {
		return new WGPURequestDeviceCallbackInfo2();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPURequestDeviceCallbackInfo2 createDirect () {
		WGPURequestDeviceCallbackInfo2 struct = new WGPURequestDeviceCallbackInfo2();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStruct> getNextInChain () {
		return nextInChain;
	}

	public WGPURequestDeviceCallbackInfo2 setNextInChain (WGPUChainedStruct... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public WGPUCallbackMode getMode () {
		return mode.get();
	}

	public WGPURequestDeviceCallbackInfo2 setMode (WGPUCallbackMode val) {
		this.mode.set(val);
		return this;
	}

	public jnr.ffi.Pointer getCallback () {
		return callback.get();
	}

	public WGPURequestDeviceCallbackInfo2 setCallback (jnr.ffi.Pointer val) {
		this.callback.set(val);
		return this;
	}

	public jnr.ffi.Pointer getUserdata1 () {
		return userdata1.get();
	}

	public WGPURequestDeviceCallbackInfo2 setUserdata1 (jnr.ffi.Pointer val) {
		this.userdata1.set(val);
		return this;
	}

	public jnr.ffi.Pointer getUserdata2 () {
		return userdata2.get();
	}

	public WGPURequestDeviceCallbackInfo2 setUserdata2 (jnr.ffi.Pointer val) {
		this.userdata2.set(val);
		return this;
	}

}
