
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDawnComputePipelineFullSubgroups extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final Unsigned32 requiresFullSubgroups = new Unsigned32();

	private WGPUDawnComputePipelineFullSubgroups () {
	}

	@Deprecated
	public WGPUDawnComputePipelineFullSubgroups (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUDawnComputePipelineFullSubgroups createHeap () {
		return new WGPUDawnComputePipelineFullSubgroups();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUDawnComputePipelineFullSubgroups createDirect () {
		WGPUDawnComputePipelineFullSubgroups struct = new WGPUDawnComputePipelineFullSubgroups();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public long getRequiresFullSubgroups () {
		return requiresFullSubgroups.get();
	}

	public WGPUDawnComputePipelineFullSubgroups setRequiresFullSubgroups (long val) {
		this.requiresFullSubgroups.set(val);
		return this;
	}

}
