
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPUExternalTextureRotation {
	Rotate0Degrees, Rotate90Degrees, Rotate180Degrees, Rotate270Degrees,
}
