
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
import jnr.ffi.Pointer;
import jnr.ffi.annotations.Delegate;

public interface WGPUCompilationInfoCallback2 {

	@Delegate
	void invoke (WGPUCompilationInfoRequestStatus status, WGPUCompilationInfo compilationInfo, Pointer userdata1,
		Pointer userdata2);
}
