
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.CStrPointer;
import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.RustCString;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUExternalTextureDescriptor extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
	private final @Nullable @CStrPointer Struct.Pointer label = new Pointer();
	private final Pointer plane0 = new Pointer();
	private final @Nullable Struct.Pointer plane1 = new Pointer();
	private final WGPUOrigin2D visibleOrigin = inner(WGPUOrigin2D.createHeap());
	private final WGPUExtent2D visibleSize = inner(WGPUExtent2D.createHeap());
	private final Unsigned32 doYuvToRgbConversionOnly = new Unsigned32();
	private final @Nullable Struct.Pointer yuvToRgbConversionMatrix = new Pointer();
	private final Pointer srcTransferFunctionParameters = new Pointer();
	private final Pointer dstTransferFunctionParameters = new Pointer();
	private final Pointer gamutConversionMatrix = new Pointer();
	private final Unsigned32 mirrored = new Unsigned32();
	private final Enum<WGPUExternalTextureRotation> rotation = new Enum<>(WGPUExternalTextureRotation.class);

	private WGPUExternalTextureDescriptor () {
	}

	@Deprecated
	public WGPUExternalTextureDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUExternalTextureDescriptor createHeap () {
		return new WGPUExternalTextureDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUExternalTextureDescriptor createDirect () {
		WGPUExternalTextureDescriptor struct = new WGPUExternalTextureDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStruct> getNextInChain () {
		return nextInChain;
	}

	public WGPUExternalTextureDescriptor setNextInChain (WGPUChainedStruct... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public java.lang.String getLabel () {
		return RustCString.fromPointer(label.get());
	}

	public WGPUExternalTextureDescriptor setLabel (java.lang.String str) {
		this.label.set(RustCString.toPointer(str));
		return this;
	}

	public jnr.ffi.Pointer getPlane0 () {
		return plane0.get();
	}

	public WGPUExternalTextureDescriptor setPlane0 (jnr.ffi.Pointer val) {
		this.plane0.set(val);
		return this;
	}

	public jnr.ffi.Pointer getPlane1 () {
		return plane1.get();
	}

	public WGPUExternalTextureDescriptor setPlane1 (jnr.ffi.Pointer val) {
		this.plane1.set(val);
		return this;
	}

	public WGPUOrigin2D getVisibleOrigin () {
		return visibleOrigin;
	}

	public WGPUExtent2D getVisibleSize () {
		return visibleSize;
	}

	public long getDoYuvToRgbConversionOnly () {
		return doYuvToRgbConversionOnly.get();
	}

	public WGPUExternalTextureDescriptor setDoYuvToRgbConversionOnly (long val) {
		this.doYuvToRgbConversionOnly.set(val);
		return this;
	}

	public jnr.ffi.Pointer getYuvToRgbConversionMatrix () {
		return yuvToRgbConversionMatrix.get();
	}

	public WGPUExternalTextureDescriptor setYuvToRgbConversionMatrix (jnr.ffi.Pointer val) {
		this.yuvToRgbConversionMatrix.set(val);
		return this;
	}

	public jnr.ffi.Pointer getSrcTransferFunctionParameters () {
		return srcTransferFunctionParameters.get();
	}

	public WGPUExternalTextureDescriptor setSrcTransferFunctionParameters (jnr.ffi.Pointer val) {
		this.srcTransferFunctionParameters.set(val);
		return this;
	}

	public jnr.ffi.Pointer getDstTransferFunctionParameters () {
		return dstTransferFunctionParameters.get();
	}

	public WGPUExternalTextureDescriptor setDstTransferFunctionParameters (jnr.ffi.Pointer val) {
		this.dstTransferFunctionParameters.set(val);
		return this;
	}

	public jnr.ffi.Pointer getGamutConversionMatrix () {
		return gamutConversionMatrix.get();
	}

	public WGPUExternalTextureDescriptor setGamutConversionMatrix (jnr.ffi.Pointer val) {
		this.gamutConversionMatrix.set(val);
		return this;
	}

	public long getMirrored () {
		return mirrored.get();
	}

	public WGPUExternalTextureDescriptor setMirrored (long val) {
		this.mirrored.set(val);
		return this;
	}

	public WGPUExternalTextureRotation getRotation () {
		return rotation.get();
	}

	public WGPUExternalTextureDescriptor setRotation (WGPUExternalTextureRotation val) {
		this.rotation.set(val);
		return this;
	}

}
