
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPUCreatePipelineAsyncStatus {
	Success, InstanceDropped, ValidationError, InternalError, DeviceLost, DeviceDestroyed, Unknown,
}
