
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUYCbCrVkDescriptor extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final Unsigned32 vkFormat = new Unsigned32();
	private final Unsigned32 vkYCbCrModel = new Unsigned32();
	private final Unsigned32 vkYCbCrRange = new Unsigned32();
	private final Unsigned32 vkComponentSwizzleRed = new Unsigned32();
	private final Unsigned32 vkComponentSwizzleGreen = new Unsigned32();
	private final Unsigned32 vkComponentSwizzleBlue = new Unsigned32();
	private final Unsigned32 vkComponentSwizzleAlpha = new Unsigned32();
	private final Unsigned32 vkXChromaOffset = new Unsigned32();
	private final Unsigned32 vkYChromaOffset = new Unsigned32();
	private final Enum<WGPUFilterMode> vkChromaFilter = new Enum<>(WGPUFilterMode.class);
	private final Unsigned32 forceExplicitReconstruction = new Unsigned32();
	private final Unsigned64 externalFormat = new Unsigned64();

	private WGPUYCbCrVkDescriptor () {
	}

	@Deprecated
	public WGPUYCbCrVkDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUYCbCrVkDescriptor createHeap () {
		return new WGPUYCbCrVkDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUYCbCrVkDescriptor createDirect () {
		WGPUYCbCrVkDescriptor struct = new WGPUYCbCrVkDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public long getVkFormat () {
		return vkFormat.get();
	}

	public WGPUYCbCrVkDescriptor setVkFormat (long val) {
		this.vkFormat.set(val);
		return this;
	}

	public long getVkYCbCrModel () {
		return vkYCbCrModel.get();
	}

	public WGPUYCbCrVkDescriptor setVkYCbCrModel (long val) {
		this.vkYCbCrModel.set(val);
		return this;
	}

	public long getVkYCbCrRange () {
		return vkYCbCrRange.get();
	}

	public WGPUYCbCrVkDescriptor setVkYCbCrRange (long val) {
		this.vkYCbCrRange.set(val);
		return this;
	}

	public long getVkComponentSwizzleRed () {
		return vkComponentSwizzleRed.get();
	}

	public WGPUYCbCrVkDescriptor setVkComponentSwizzleRed (long val) {
		this.vkComponentSwizzleRed.set(val);
		return this;
	}

	public long getVkComponentSwizzleGreen () {
		return vkComponentSwizzleGreen.get();
	}

	public WGPUYCbCrVkDescriptor setVkComponentSwizzleGreen (long val) {
		this.vkComponentSwizzleGreen.set(val);
		return this;
	}

	public long getVkComponentSwizzleBlue () {
		return vkComponentSwizzleBlue.get();
	}

	public WGPUYCbCrVkDescriptor setVkComponentSwizzleBlue (long val) {
		this.vkComponentSwizzleBlue.set(val);
		return this;
	}

	public long getVkComponentSwizzleAlpha () {
		return vkComponentSwizzleAlpha.get();
	}

	public WGPUYCbCrVkDescriptor setVkComponentSwizzleAlpha (long val) {
		this.vkComponentSwizzleAlpha.set(val);
		return this;
	}

	public long getVkXChromaOffset () {
		return vkXChromaOffset.get();
	}

	public WGPUYCbCrVkDescriptor setVkXChromaOffset (long val) {
		this.vkXChromaOffset.set(val);
		return this;
	}

	public long getVkYChromaOffset () {
		return vkYChromaOffset.get();
	}

	public WGPUYCbCrVkDescriptor setVkYChromaOffset (long val) {
		this.vkYChromaOffset.set(val);
		return this;
	}

	public WGPUFilterMode getVkChromaFilter () {
		return vkChromaFilter.get();
	}

	public WGPUYCbCrVkDescriptor setVkChromaFilter (WGPUFilterMode val) {
		this.vkChromaFilter.set(val);
		return this;
	}

	public long getForceExplicitReconstruction () {
		return forceExplicitReconstruction.get();
	}

	public WGPUYCbCrVkDescriptor setForceExplicitReconstruction (long val) {
		this.forceExplicitReconstruction.set(val);
		return this;
	}

	public @jnr.ffi.types.u_int64_t long getExternalFormat () {
		return externalFormat.get();
	}

	public WGPUYCbCrVkDescriptor setExternalFormat (@jnr.ffi.types.u_int64_t long val) {
		this.externalFormat.set(val);
		return this;
	}

}
