
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPUBufferMapAsyncStatus {
	Success, InstanceDropped, ValidationError, Unknown, DeviceLost, DestroyedBeforeCallback, UnmappedBeforeCallback, MappingAlreadyPending, OffsetOutOfRange, SizeOutOfRange,
}
