
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUPipelineLayoutPixelLocalStorage extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final Unsigned64 totalPixelLocalStorageSize = new Unsigned64();
	private final size_t storageAttachmentCount = new size_t();
	private final DynamicStructRef<WGPUPipelineLayoutStorageAttachment> storageAttachments = new DynamicStructRef<>(
		WGPUPipelineLayoutStorageAttachment.class);

	private WGPUPipelineLayoutPixelLocalStorage () {
	}

	@Deprecated
	public WGPUPipelineLayoutPixelLocalStorage (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUPipelineLayoutPixelLocalStorage createHeap () {
		return new WGPUPipelineLayoutPixelLocalStorage();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUPipelineLayoutPixelLocalStorage createDirect () {
		WGPUPipelineLayoutPixelLocalStorage struct = new WGPUPipelineLayoutPixelLocalStorage();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public @jnr.ffi.types.u_int64_t long getTotalPixelLocalStorageSize () {
		return totalPixelLocalStorageSize.get();
	}

	public WGPUPipelineLayoutPixelLocalStorage setTotalPixelLocalStorageSize (@jnr.ffi.types.u_int64_t long val) {
		this.totalPixelLocalStorageSize.set(val);
		return this;
	}

	public long getStorageAttachmentCount () {
		return storageAttachmentCount.get();
	}

	public WGPUPipelineLayoutPixelLocalStorage setStorageAttachmentCount (long val) {
		this.storageAttachmentCount.set(val);
		return this;
	}

	public DynamicStructRef<WGPUPipelineLayoutStorageAttachment> getStorageAttachments () {
		return storageAttachments;
	}

	public WGPUPipelineLayoutPixelLocalStorage setStorageAttachments (WGPUPipelineLayoutStorageAttachment... x) {
		if (x.length == 0 || x[0] == null) {
			this.storageAttachments.set(JavaWebGPU.createNullPointer());
		} else {
			this.storageAttachments.set(x);
		}
		return this;
	}

}
