
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedTextureMemoryProperties extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStructOut> nextInChain = new DynamicStructRef<>(WGPUChainedStructOut.class);
	private final Unsigned32 usage = new Unsigned32();
	private final WGPUExtent3D size = inner(WGPUExtent3D.createHeap());
	private final Enum<WGPUTextureFormat> format = new Enum<>(WGPUTextureFormat.class);

	private WGPUSharedTextureMemoryProperties () {
	}

	@Deprecated
	public WGPUSharedTextureMemoryProperties (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUSharedTextureMemoryProperties createHeap () {
		return new WGPUSharedTextureMemoryProperties();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUSharedTextureMemoryProperties createDirect () {
		WGPUSharedTextureMemoryProperties struct = new WGPUSharedTextureMemoryProperties();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStructOut> getNextInChain () {
		return nextInChain;
	}

	public WGPUSharedTextureMemoryProperties setNextInChain (WGPUChainedStructOut... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public long getUsage () {
		return usage.get();
	}

	public WGPUSharedTextureMemoryProperties setUsage (long val) {
		this.usage.set(val);
		return this;
	}

	public WGPUExtent3D getSize () {
		return size;
	}

	public WGPUTextureFormat getFormat () {
		return format.get();
	}

	public WGPUSharedTextureMemoryProperties setFormat (WGPUTextureFormat val) {
		this.format.set(val);
		return this;
	}

}
