
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedTextureMemoryDmaBufDescriptor extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final WGPUExtent3D size = inner(WGPUExtent3D.createHeap());
	private final Unsigned32 drmFormat = new Unsigned32();
	private final Unsigned64 drmModifier = new Unsigned64();
	private final size_t planeCount = new size_t();
	private final DynamicStructRef<WGPUSharedTextureMemoryDmaBufPlane> planes = new DynamicStructRef<>(
		WGPUSharedTextureMemoryDmaBufPlane.class);

	private WGPUSharedTextureMemoryDmaBufDescriptor () {
	}

	@Deprecated
	public WGPUSharedTextureMemoryDmaBufDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUSharedTextureMemoryDmaBufDescriptor createHeap () {
		return new WGPUSharedTextureMemoryDmaBufDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUSharedTextureMemoryDmaBufDescriptor createDirect () {
		WGPUSharedTextureMemoryDmaBufDescriptor struct = new WGPUSharedTextureMemoryDmaBufDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public WGPUExtent3D getSize () {
		return size;
	}

	public long getDrmFormat () {
		return drmFormat.get();
	}

	public WGPUSharedTextureMemoryDmaBufDescriptor setDrmFormat (long val) {
		this.drmFormat.set(val);
		return this;
	}

	public @jnr.ffi.types.u_int64_t long getDrmModifier () {
		return drmModifier.get();
	}

	public WGPUSharedTextureMemoryDmaBufDescriptor setDrmModifier (@jnr.ffi.types.u_int64_t long val) {
		this.drmModifier.set(val);
		return this;
	}

	public long getPlaneCount () {
		return planeCount.get();
	}

	public WGPUSharedTextureMemoryDmaBufDescriptor setPlaneCount (long val) {
		this.planeCount.set(val);
		return this;
	}

	public DynamicStructRef<WGPUSharedTextureMemoryDmaBufPlane> getPlanes () {
		return planes;
	}

	public WGPUSharedTextureMemoryDmaBufDescriptor setPlanes (WGPUSharedTextureMemoryDmaBufPlane... x) {
		if (x.length == 0 || x[0] == null) {
			this.planes.set(JavaWebGPU.createNullPointer());
		} else {
			this.planes.set(x);
		}
		return this;
	}

}
