
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedTextureMemoryAHardwareBufferProperties extends WgpuJavaStruct {

	private final WGPUChainedStructOut chain = inner(WGPUChainedStructOut.createHeap());
	private final WGPUYCbCrVkDescriptor yCbCrInfo = inner(WGPUYCbCrVkDescriptor.createHeap());

	private WGPUSharedTextureMemoryAHardwareBufferProperties () {
	}

	@Deprecated
	public WGPUSharedTextureMemoryAHardwareBufferProperties (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUSharedTextureMemoryAHardwareBufferProperties createHeap () {
		return new WGPUSharedTextureMemoryAHardwareBufferProperties();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUSharedTextureMemoryAHardwareBufferProperties createDirect () {
		WGPUSharedTextureMemoryAHardwareBufferProperties struct = new WGPUSharedTextureMemoryAHardwareBufferProperties();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStructOut getChain () {
		return chain;
	}

	public WGPUYCbCrVkDescriptor getYCbCrInfo () {
		return yCbCrInfo;
	}

}
