
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDawnBufferDescriptorErrorInfoFromWireClient extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final Unsigned32 outOfMemory = new Unsigned32();

	private WGPUDawnBufferDescriptorErrorInfoFromWireClient () {
	}

	@Deprecated
	public WGPUDawnBufferDescriptorErrorInfoFromWireClient (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUDawnBufferDescriptorErrorInfoFromWireClient createHeap () {
		return new WGPUDawnBufferDescriptorErrorInfoFromWireClient();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUDawnBufferDescriptorErrorInfoFromWireClient createDirect () {
		WGPUDawnBufferDescriptorErrorInfoFromWireClient struct = new WGPUDawnBufferDescriptorErrorInfoFromWireClient();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public long getOutOfMemory () {
		return outOfMemory.get();
	}

	public WGPUDawnBufferDescriptorErrorInfoFromWireClient setOutOfMemory (long val) {
		this.outOfMemory.set(val);
		return this;
	}

}
