
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.CStrPointer;
import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.RustCString;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUComputePipelineDescriptor extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
	private final @Nullable @CStrPointer Struct.Pointer label = new Pointer();
	private final @Nullable Struct.Pointer layout = new Pointer();
	private final WGPUProgrammableStageDescriptor compute = inner(WGPUProgrammableStageDescriptor.createHeap());

	private WGPUComputePipelineDescriptor () {
	}

	@Deprecated
	public WGPUComputePipelineDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUComputePipelineDescriptor createHeap () {
		return new WGPUComputePipelineDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUComputePipelineDescriptor createDirect () {
		WGPUComputePipelineDescriptor struct = new WGPUComputePipelineDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStruct> getNextInChain () {
		return nextInChain;
	}

	public WGPUComputePipelineDescriptor setNextInChain (WGPUChainedStruct... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public java.lang.String getLabel () {
		return RustCString.fromPointer(label.get());
	}

	public WGPUComputePipelineDescriptor setLabel (java.lang.String str) {
		this.label.set(RustCString.toPointer(str));
		return this;
	}

	public jnr.ffi.Pointer getLayout () {
		return layout.get();
	}

	public WGPUComputePipelineDescriptor setLayout (jnr.ffi.Pointer val) {
		this.layout.set(val);
		return this;
	}

	public WGPUProgrammableStageDescriptor getCompute () {
		return compute;
	}

}
