
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPURenderPassTimestampWrites extends WgpuJavaStruct {

	private final Pointer querySet = new Pointer();
	private final Unsigned32 beginningOfPassWriteIndex = new Unsigned32();
	private final Unsigned32 endOfPassWriteIndex = new Unsigned32();

	private WGPURenderPassTimestampWrites () {
	}

	@Deprecated
	public WGPURenderPassTimestampWrites (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPURenderPassTimestampWrites createHeap () {
		return new WGPURenderPassTimestampWrites();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPURenderPassTimestampWrites createDirect () {
		WGPURenderPassTimestampWrites struct = new WGPURenderPassTimestampWrites();
		struct.useDirectMemory();
		return struct;
	}

	public jnr.ffi.Pointer getQuerySet () {
		return querySet.get();
	}

	public WGPURenderPassTimestampWrites setQuerySet (jnr.ffi.Pointer val) {
		this.querySet.set(val);
		return this;
	}

	public long getBeginningOfPassWriteIndex () {
		return beginningOfPassWriteIndex.get();
	}

	public WGPURenderPassTimestampWrites setBeginningOfPassWriteIndex (long val) {
		this.beginningOfPassWriteIndex.set(val);
		return this;
	}

	public long getEndOfPassWriteIndex () {
		return endOfPassWriteIndex.get();
	}

	public WGPURenderPassTimestampWrites setEndOfPassWriteIndex (long val) {
		this.endOfPassWriteIndex.set(val);
		return this;
	}

}
