
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPUWaitStatus {
	Success, TimedOut, UnsupportedTimeout, UnsupportedCount, UnsupportedMixedSources, Unknown,
}
