
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPUTextureAspect {
	Undefined, All, StencilOnly, DepthOnly, Plane0Only, Plane1Only, Plane2Only,
}
