
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedTextureMemoryEGLImageDescriptor extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final Pointer image = new Pointer();

	private WGPUSharedTextureMemoryEGLImageDescriptor () {
	}

	@Deprecated
	public WGPUSharedTextureMemoryEGLImageDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUSharedTextureMemoryEGLImageDescriptor createHeap () {
		return new WGPUSharedTextureMemoryEGLImageDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUSharedTextureMemoryEGLImageDescriptor createDirect () {
		WGPUSharedTextureMemoryEGLImageDescriptor struct = new WGPUSharedTextureMemoryEGLImageDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public jnr.ffi.Pointer getImage () {
		return image.get();
	}

	public WGPUSharedTextureMemoryEGLImageDescriptor setImage (jnr.ffi.Pointer val) {
		this.image.set(val);
		return this;
	}

}
