
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedTextureMemoryIOSurfaceDescriptor extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final Pointer ioSurface = new Pointer();

	private WGPUSharedTextureMemoryIOSurfaceDescriptor () {
	}

	@Deprecated
	public WGPUSharedTextureMemoryIOSurfaceDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUSharedTextureMemoryIOSurfaceDescriptor createHeap () {
		return new WGPUSharedTextureMemoryIOSurfaceDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUSharedTextureMemoryIOSurfaceDescriptor createDirect () {
		WGPUSharedTextureMemoryIOSurfaceDescriptor struct = new WGPUSharedTextureMemoryIOSurfaceDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public jnr.ffi.Pointer getIoSurface () {
		return ioSurface.get();
	}

	public WGPUSharedTextureMemoryIOSurfaceDescriptor setIoSurface (jnr.ffi.Pointer val) {
		this.ioSurface.set(val);
		return this;
	}

}
