
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
import jnr.ffi.Pointer;
import jnr.ffi.annotations.Delegate;

public interface WGPUDeviceLostCallbackNew {

	@Delegate
	void invoke (Pointer device, WGPUDeviceLostReason reason, String message, Pointer userdata);
}
