
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUImageCopyTexture extends WgpuJavaStruct {

	private final Pointer texture = new Pointer();
	private final Unsigned32 mipLevel = new Unsigned32();
	private final WGPUOrigin3D origin = inner(WGPUOrigin3D.createHeap());
	private final Enum<WGPUTextureAspect> aspect = new Enum<>(WGPUTextureAspect.class);

	private WGPUImageCopyTexture () {
	}

	@Deprecated
	public WGPUImageCopyTexture (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUImageCopyTexture createHeap () {
		return new WGPUImageCopyTexture();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUImageCopyTexture createDirect () {
		WGPUImageCopyTexture struct = new WGPUImageCopyTexture();
		struct.useDirectMemory();
		return struct;
	}

	public jnr.ffi.Pointer getTexture () {
		return texture.get();
	}

	public WGPUImageCopyTexture setTexture (jnr.ffi.Pointer val) {
		this.texture.set(val);
		return this;
	}

	public long getMipLevel () {
		return mipLevel.get();
	}

	public WGPUImageCopyTexture setMipLevel (long val) {
		this.mipLevel.set(val);
		return this;
	}

	public WGPUOrigin3D getOrigin () {
		return origin;
	}

	public WGPUTextureAspect getAspect () {
		return aspect.get();
	}

	public WGPUImageCopyTexture setAspect (WGPUTextureAspect val) {
		this.aspect.set(val);
		return this;
	}

}
