
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
import jnr.ffi.Pointer;
import jnr.ffi.annotations.Delegate;

public interface WGPUDeviceLostCallback {

	@Delegate
	void invoke (WGPUDeviceLostReason reason, String message, Pointer userdata);
}
