
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.CStrPointer;
import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.RustCString;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUConstantEntry extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
	private final @CStrPointer Pointer key = new Pointer();
	private final Double value = new Double();

	private WGPUConstantEntry () {
	}

	@Deprecated
	public WGPUConstantEntry (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUConstantEntry createHeap () {
		return new WGPUConstantEntry();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUConstantEntry createDirect () {
		WGPUConstantEntry struct = new WGPUConstantEntry();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStruct> getNextInChain () {
		return nextInChain;
	}

	public WGPUConstantEntry setNextInChain (WGPUChainedStruct... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public java.lang.String getKey () {
		return RustCString.fromPointer(key.get());
	}

	public WGPUConstantEntry setKey (java.lang.String str) {
		this.key.set(RustCString.toPointer(str));
		return this;
	}

	public double getValue () {
		return value.get();
	}

	public WGPUConstantEntry setValue (double val) {
		this.value.set(val);
		return this;
	}

}
