
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUExtent3D extends WgpuJavaStruct {

	private final Unsigned32 width = new Unsigned32();
	private final Unsigned32 height = new Unsigned32();
	private final Unsigned32 depthOrArrayLayers = new Unsigned32();

	private WGPUExtent3D () {
	}

	@Deprecated
	public WGPUExtent3D (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUExtent3D createHeap () {
		return new WGPUExtent3D();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUExtent3D createDirect () {
		WGPUExtent3D struct = new WGPUExtent3D();
		struct.useDirectMemory();
		return struct;
	}

	public long getWidth () {
		return width.get();
	}

	public WGPUExtent3D setWidth (long val) {
		this.width.set(val);
		return this;
	}

	public long getHeight () {
		return height.get();
	}

	public WGPUExtent3D setHeight (long val) {
		this.height.set(val);
		return this;
	}

	public long getDepthOrArrayLayers () {
		return depthOrArrayLayers.get();
	}

	public WGPUExtent3D setDepthOrArrayLayers (long val) {
		this.depthOrArrayLayers.set(val);
		return this;
	}

}
