
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDawnTogglesDescriptor extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final size_t enabledToggleCount = new size_t();
	private final Pointer enabledToggles = new Pointer();
	private final size_t disabledToggleCount = new size_t();
	private final Pointer disabledToggles = new Pointer();

	private WGPUDawnTogglesDescriptor () {
	}

	@Deprecated
	public WGPUDawnTogglesDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUDawnTogglesDescriptor createHeap () {
		return new WGPUDawnTogglesDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUDawnTogglesDescriptor createDirect () {
		WGPUDawnTogglesDescriptor struct = new WGPUDawnTogglesDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public long getEnabledToggleCount () {
		return enabledToggleCount.get();
	}

	public WGPUDawnTogglesDescriptor setEnabledToggleCount (long val) {
		this.enabledToggleCount.set(val);
		return this;
	}

	public jnr.ffi.Pointer getEnabledToggles () {
		return enabledToggles.get();
	}

	public WGPUDawnTogglesDescriptor setEnabledToggles (jnr.ffi.Pointer val) {
		this.enabledToggles.set(val);
		return this;
	}

	public long getDisabledToggleCount () {
		return disabledToggleCount.get();
	}

	public WGPUDawnTogglesDescriptor setDisabledToggleCount (long val) {
		this.disabledToggleCount.set(val);
		return this;
	}

	public jnr.ffi.Pointer getDisabledToggles () {
		return disabledToggles.get();
	}

	public WGPUDawnTogglesDescriptor setDisabledToggles (jnr.ffi.Pointer val) {
		this.disabledToggles.set(val);
		return this;
	}

}
