
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUTextureBindingLayout extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
	private final Enum<WGPUTextureSampleType> sampleType = new Enum<>(WGPUTextureSampleType.class);
	private final Enum<WGPUTextureViewDimension> viewDimension = new Enum<>(WGPUTextureViewDimension.class);
	private final Unsigned32 multisampled = new Unsigned32();

	private WGPUTextureBindingLayout () {
	}

	@Deprecated
	public WGPUTextureBindingLayout (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUTextureBindingLayout createHeap () {
		return new WGPUTextureBindingLayout();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUTextureBindingLayout createDirect () {
		WGPUTextureBindingLayout struct = new WGPUTextureBindingLayout();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStruct> getNextInChain () {
		return nextInChain;
	}

	public WGPUTextureBindingLayout setNextInChain (WGPUChainedStruct... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public WGPUTextureSampleType getSampleType () {
		return sampleType.get();
	}

	public WGPUTextureBindingLayout setSampleType (WGPUTextureSampleType val) {
		this.sampleType.set(val);
		return this;
	}

	public WGPUTextureViewDimension getViewDimension () {
		return viewDimension.get();
	}

	public WGPUTextureBindingLayout setViewDimension (WGPUTextureViewDimension val) {
		this.viewDimension.set(val);
		return this;
	}

	public long getMultisampled () {
		return multisampled.get();
	}

	public WGPUTextureBindingLayout setMultisampled (long val) {
		this.multisampled.set(val);
		return this;
	}

}
