
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
import jnr.ffi.Pointer;
import jnr.ffi.annotations.Delegate;

public interface WGPUDawnLoadCacheDataFunction {

	@Delegate
	void invoke (Pointer key, long keySize, Pointer value, long valueSize, Pointer userdata);
}
