
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPURenderPassColorAttachment extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
	private final @Nullable Struct.Pointer view = new Pointer();
	private final Unsigned32 depthSlice = new Unsigned32();
	private final @Nullable Struct.Pointer resolveTarget = new Pointer();
	private final Enum<WGPULoadOp> loadOp = new Enum<>(WGPULoadOp.class);
	private final Enum<WGPUStoreOp> storeOp = new Enum<>(WGPUStoreOp.class);
	private final WGPUColor clearValue = inner(WGPUColor.createHeap());

	private WGPURenderPassColorAttachment () {
	}

	@Deprecated
	public WGPURenderPassColorAttachment (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPURenderPassColorAttachment createHeap () {
		return new WGPURenderPassColorAttachment();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPURenderPassColorAttachment createDirect () {
		WGPURenderPassColorAttachment struct = new WGPURenderPassColorAttachment();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStruct> getNextInChain () {
		return nextInChain;
	}

	public WGPURenderPassColorAttachment setNextInChain (WGPUChainedStruct... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public jnr.ffi.Pointer getView () {
		return view.get();
	}

	public WGPURenderPassColorAttachment setView (jnr.ffi.Pointer val) {
		this.view.set(val);
		return this;
	}

	public long getDepthSlice () {
		return depthSlice.get();
	}

	public WGPURenderPassColorAttachment setDepthSlice (long val) {
		this.depthSlice.set(val);
		return this;
	}

	public jnr.ffi.Pointer getResolveTarget () {
		return resolveTarget.get();
	}

	public WGPURenderPassColorAttachment setResolveTarget (jnr.ffi.Pointer val) {
		this.resolveTarget.set(val);
		return this;
	}

	public WGPULoadOp getLoadOp () {
		return loadOp.get();
	}

	public WGPURenderPassColorAttachment setLoadOp (WGPULoadOp val) {
		this.loadOp.set(val);
		return this;
	}

	public WGPUStoreOp getStoreOp () {
		return storeOp.get();
	}

	public WGPURenderPassColorAttachment setStoreOp (WGPUStoreOp val) {
		this.storeOp.set(val);
		return this;
	}

	public WGPUColor getClearValue () {
		return clearValue;
	}

}
