
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUShaderStage {
	public static final int None = 0x0;
	public static final int Vertex = 0x1;
	public static final int Fragment = 0x2;
	public static final int Compute = 0x4;
}
