
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDawnRenderPassColorAttachmentRenderToSingleSampled extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final Unsigned32 implicitSampleCount = new Unsigned32();

	private WGPUDawnRenderPassColorAttachmentRenderToSingleSampled () {
	}

	@Deprecated
	public WGPUDawnRenderPassColorAttachmentRenderToSingleSampled (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUDawnRenderPassColorAttachmentRenderToSingleSampled createHeap () {
		return new WGPUDawnRenderPassColorAttachmentRenderToSingleSampled();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUDawnRenderPassColorAttachmentRenderToSingleSampled createDirect () {
		WGPUDawnRenderPassColorAttachmentRenderToSingleSampled struct = new WGPUDawnRenderPassColorAttachmentRenderToSingleSampled();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public long getImplicitSampleCount () {
		return implicitSampleCount.get();
	}

	public WGPUDawnRenderPassColorAttachmentRenderToSingleSampled setImplicitSampleCount (long val) {
		this.implicitSampleCount.set(val);
		return this;
	}

}
