
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUOrigin2D extends WgpuJavaStruct {

	private final Unsigned32 x = new Unsigned32();
	private final Unsigned32 y = new Unsigned32();

	private WGPUOrigin2D () {
	}

	@Deprecated
	public WGPUOrigin2D (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUOrigin2D createHeap () {
		return new WGPUOrigin2D();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUOrigin2D createDirect () {
		WGPUOrigin2D struct = new WGPUOrigin2D();
		struct.useDirectMemory();
		return struct;
	}

	public long getX () {
		return x.get();
	}

	public WGPUOrigin2D setX (long val) {
		this.x.set(val);
		return this;
	}

	public long getY () {
		return y.get();
	}

	public WGPUOrigin2D setY (long val) {
		this.y.set(val);
		return this;
	}

}
