
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSamplerBindingLayout extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
	private final Enum<WGPUSamplerBindingType> type = new Enum<>(WGPUSamplerBindingType.class);

	private WGPUSamplerBindingLayout () {
	}

	@Deprecated
	public WGPUSamplerBindingLayout (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUSamplerBindingLayout createHeap () {
		return new WGPUSamplerBindingLayout();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUSamplerBindingLayout createDirect () {
		WGPUSamplerBindingLayout struct = new WGPUSamplerBindingLayout();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStruct> getNextInChain () {
		return nextInChain;
	}

	public WGPUSamplerBindingLayout setNextInChain (WGPUChainedStruct... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public WGPUSamplerBindingType getType () {
		return type.get();
	}

	public WGPUSamplerBindingLayout setType (WGPUSamplerBindingType val) {
		this.type.set(val);
		return this;
	}

}
