
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final Unsigned32 dedicatedAllocation = new Unsigned32();

	private WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor () {
	}

	@Deprecated
	public WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor createHeap () {
		return new WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor createDirect () {
		WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor struct = new WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public long getDedicatedAllocation () {
		return dedicatedAllocation.get();
	}

	public WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor setDedicatedAllocation (long val) {
		this.dedicatedAllocation.set(val);
		return this;
	}

}
