
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUWGSLFeatureName {
	public static final int Undefined = 0x0;
	public static final int ReadonlyAndReadwriteStorageTextures = 0x1;
	public static final int Packed4x8IntegerDotProduct = 0x2;
	public static final int UnrestrictedPointerParameters = 0x3;
	public static final int PointerCompositeAccess = 0x4;
	public static final int ChromiumTestingUnimplemented = 0x3e8;
	public static final int ChromiumTestingUnsafeExperimental = 0x3e9;
	public static final int ChromiumTestingExperimental = 0x3ea;
	public static final int ChromiumTestingShippedWithKillswitch = 0x3eb;
	public static final int ChromiumTestingShipped = 0x3ec;
}
