
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.CStrPointer;
import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.RustCString;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPURenderBundleEncoderDescriptor extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
	private final @Nullable @CStrPointer Struct.Pointer label = new Pointer();
	private final size_t colorFormatCount = new size_t();
	private final Pointer colorFormats = new Pointer();
	private final Enum<WGPUTextureFormat> depthStencilFormat = new Enum<>(WGPUTextureFormat.class);
	private final Unsigned32 sampleCount = new Unsigned32();
	private final Unsigned32 depthReadOnly = new Unsigned32();
	private final Unsigned32 stencilReadOnly = new Unsigned32();

	private WGPURenderBundleEncoderDescriptor () {
	}

	@Deprecated
	public WGPURenderBundleEncoderDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPURenderBundleEncoderDescriptor createHeap () {
		return new WGPURenderBundleEncoderDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPURenderBundleEncoderDescriptor createDirect () {
		WGPURenderBundleEncoderDescriptor struct = new WGPURenderBundleEncoderDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStruct> getNextInChain () {
		return nextInChain;
	}

	public WGPURenderBundleEncoderDescriptor setNextInChain (WGPUChainedStruct... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public java.lang.String getLabel () {
		return RustCString.fromPointer(label.get());
	}

	public WGPURenderBundleEncoderDescriptor setLabel (java.lang.String str) {
		this.label.set(RustCString.toPointer(str));
		return this;
	}

	public long getColorFormatCount () {
		return colorFormatCount.get();
	}

	public WGPURenderBundleEncoderDescriptor setColorFormatCount (long val) {
		this.colorFormatCount.set(val);
		return this;
	}

	public jnr.ffi.Pointer getColorFormats () {
		return colorFormats.get();
	}

	public WGPURenderBundleEncoderDescriptor setColorFormats (jnr.ffi.Pointer val) {
		this.colorFormats.set(val);
		return this;
	}

	public WGPUTextureFormat getDepthStencilFormat () {
		return depthStencilFormat.get();
	}

	public WGPURenderBundleEncoderDescriptor setDepthStencilFormat (WGPUTextureFormat val) {
		this.depthStencilFormat.set(val);
		return this;
	}

	public long getSampleCount () {
		return sampleCount.get();
	}

	public WGPURenderBundleEncoderDescriptor setSampleCount (long val) {
		this.sampleCount.set(val);
		return this;
	}

	public long getDepthReadOnly () {
		return depthReadOnly.get();
	}

	public WGPURenderBundleEncoderDescriptor setDepthReadOnly (long val) {
		this.depthReadOnly.set(val);
		return this;
	}

	public long getStencilReadOnly () {
		return stencilReadOnly.get();
	}

	public WGPURenderBundleEncoderDescriptor setStencilReadOnly (long val) {
		this.stencilReadOnly.set(val);
		return this;
	}

}
