
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedFenceExportInfo extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStructOut> nextInChain = new DynamicStructRef<>(WGPUChainedStructOut.class);
	private final Enum<WGPUSharedFenceType> type = new Enum<>(WGPUSharedFenceType.class);

	private WGPUSharedFenceExportInfo () {
	}

	@Deprecated
	public WGPUSharedFenceExportInfo (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUSharedFenceExportInfo createHeap () {
		return new WGPUSharedFenceExportInfo();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUSharedFenceExportInfo createDirect () {
		WGPUSharedFenceExportInfo struct = new WGPUSharedFenceExportInfo();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStructOut> getNextInChain () {
		return nextInChain;
	}

	public WGPUSharedFenceExportInfo setNextInChain (WGPUChainedStructOut... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public WGPUSharedFenceType getType () {
		return type.get();
	}

	public WGPUSharedFenceExportInfo setType (WGPUSharedFenceType val) {
		this.type.set(val);
		return this;
	}

}
