
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDrmFormatCapabilities extends WgpuJavaStruct {

	private final WGPUChainedStructOut chain = inner(WGPUChainedStructOut.createHeap());
	private final size_t propertiesCount = new size_t();
	private final DynamicStructRef<WGPUDrmFormatProperties> properties = new DynamicStructRef<>(WGPUDrmFormatProperties.class);

	private WGPUDrmFormatCapabilities () {
	}

	@Deprecated
	public WGPUDrmFormatCapabilities (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUDrmFormatCapabilities createHeap () {
		return new WGPUDrmFormatCapabilities();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUDrmFormatCapabilities createDirect () {
		WGPUDrmFormatCapabilities struct = new WGPUDrmFormatCapabilities();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStructOut getChain () {
		return chain;
	}

	public long getPropertiesCount () {
		return propertiesCount.get();
	}

	public WGPUDrmFormatCapabilities setPropertiesCount (long val) {
		this.propertiesCount.set(val);
		return this;
	}

	public DynamicStructRef<WGPUDrmFormatProperties> getProperties () {
		return properties;
	}

	public WGPUDrmFormatCapabilities setProperties (WGPUDrmFormatProperties... x) {
		if (x.length == 0 || x[0] == null) {
			this.properties.set(JavaWebGPU.createNullPointer());
		} else {
			this.properties.set(x);
		}
		return this;
	}

}
