
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUBufferUsage {
	public static final int None = 0x0;
	public static final int MapRead = 0x1;
	public static final int MapWrite = 0x2;
	public static final int CopySrc = 0x4;
	public static final int CopyDst = 0x8;
	public static final int Index = 0x10;
	public static final int Vertex = 0x20;
	public static final int Uniform = 0x40;
	public static final int Storage = 0x80;
	public static final int Indirect = 0x100;
	public static final int QueryResolve = 0x200;
}
