
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedTextureMemoryDXGISharedHandleDescriptor extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final Pointer handle = new Pointer();
	private final Unsigned32 useKeyedMutex = new Unsigned32();

	private WGPUSharedTextureMemoryDXGISharedHandleDescriptor () {
	}

	@Deprecated
	public WGPUSharedTextureMemoryDXGISharedHandleDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUSharedTextureMemoryDXGISharedHandleDescriptor createHeap () {
		return new WGPUSharedTextureMemoryDXGISharedHandleDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUSharedTextureMemoryDXGISharedHandleDescriptor createDirect () {
		WGPUSharedTextureMemoryDXGISharedHandleDescriptor struct = new WGPUSharedTextureMemoryDXGISharedHandleDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public jnr.ffi.Pointer getHandle () {
		return handle.get();
	}

	public WGPUSharedTextureMemoryDXGISharedHandleDescriptor setHandle (jnr.ffi.Pointer val) {
		this.handle.set(val);
		return this;
	}

	public long getUseKeyedMutex () {
		return useKeyedMutex.get();
	}

	public WGPUSharedTextureMemoryDXGISharedHandleDescriptor setUseKeyedMutex (long val) {
		this.useKeyedMutex.set(val);
		return this;
	}

}
