
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUFutureWaitInfo extends WgpuJavaStruct {

	private final WGPUFuture future = inner(WGPUFuture.createHeap());
	private final Unsigned32 completed = new Unsigned32();

	private WGPUFutureWaitInfo () {
	}

	@Deprecated
	public WGPUFutureWaitInfo (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUFutureWaitInfo createHeap () {
		return new WGPUFutureWaitInfo();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUFutureWaitInfo createDirect () {
		WGPUFutureWaitInfo struct = new WGPUFutureWaitInfo();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUFuture getFuture () {
		return future;
	}

	public long getCompleted () {
		return completed.get();
	}

	public WGPUFutureWaitInfo setCompleted (long val) {
		this.completed.set(val);
		return this;
	}

}
