
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUColor extends WgpuJavaStruct {

	private final Double r = new Double();
	private final Double g = new Double();
	private final Double b = new Double();
	private final Double a = new Double();

	private WGPUColor () {
	}

	@Deprecated
	public WGPUColor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUColor createHeap () {
		return new WGPUColor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUColor createDirect () {
		WGPUColor struct = new WGPUColor();
		struct.useDirectMemory();
		return struct;
	}

	public double getR () {
		return r.get();
	}

	public WGPUColor setR (double val) {
		this.r.set(val);
		return this;
	}

	public double getG () {
		return g.get();
	}

	public WGPUColor setG (double val) {
		this.g.set(val);
		return this;
	}

	public double getB () {
		return b.get();
	}

	public WGPUColor setB (double val) {
		this.b.set(val);
		return this;
	}

	public double getA () {
		return a.get();
	}

	public WGPUColor setA (double val) {
		this.a.set(val);
		return this;
	}

}
