
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUOrigin3D extends WgpuJavaStruct {

	private final Unsigned32 x = new Unsigned32();
	private final Unsigned32 y = new Unsigned32();
	private final Unsigned32 z = new Unsigned32();

	private WGPUOrigin3D () {
	}

	@Deprecated
	public WGPUOrigin3D (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUOrigin3D createHeap () {
		return new WGPUOrigin3D();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUOrigin3D createDirect () {
		WGPUOrigin3D struct = new WGPUOrigin3D();
		struct.useDirectMemory();
		return struct;
	}

	public long getX () {
		return x.get();
	}

	public WGPUOrigin3D setX (long val) {
		this.x.set(val);
		return this;
	}

	public long getY () {
		return y.get();
	}

	public WGPUOrigin3D setY (long val) {
		this.y.set(val);
		return this;
	}

	public long getZ () {
		return z.get();
	}

	public WGPUOrigin3D setZ (long val) {
		this.z.set(val);
		return this;
	}

}
