
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUTextureBindingViewDimensionDescriptor extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final Enum<WGPUTextureViewDimension> textureBindingViewDimension = new Enum<>(WGPUTextureViewDimension.class);

	private WGPUTextureBindingViewDimensionDescriptor () {
	}

	@Deprecated
	public WGPUTextureBindingViewDimensionDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUTextureBindingViewDimensionDescriptor createHeap () {
		return new WGPUTextureBindingViewDimensionDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUTextureBindingViewDimensionDescriptor createDirect () {
		WGPUTextureBindingViewDimensionDescriptor struct = new WGPUTextureBindingViewDimensionDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public WGPUTextureViewDimension getTextureBindingViewDimension () {
		return textureBindingViewDimension.get();
	}

	public WGPUTextureBindingViewDimensionDescriptor setTextureBindingViewDimension (WGPUTextureViewDimension val) {
		this.textureBindingViewDimension.set(val);
		return this;
	}

}
