
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUBufferHostMappedPointer extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final Pointer pointer = new Pointer();
	private final Pointer disposeCallback = new Pointer();
	private final Pointer userdata = new Pointer();

	private WGPUBufferHostMappedPointer () {
	}

	@Deprecated
	public WGPUBufferHostMappedPointer (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUBufferHostMappedPointer createHeap () {
		return new WGPUBufferHostMappedPointer();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUBufferHostMappedPointer createDirect () {
		WGPUBufferHostMappedPointer struct = new WGPUBufferHostMappedPointer();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public jnr.ffi.Pointer getPointer () {
		return pointer.get();
	}

	public WGPUBufferHostMappedPointer setPointer (jnr.ffi.Pointer val) {
		this.pointer.set(val);
		return this;
	}

	public jnr.ffi.Pointer getDisposeCallback () {
		return disposeCallback.get();
	}

	public WGPUBufferHostMappedPointer setDisposeCallback (jnr.ffi.Pointer val) {
		this.disposeCallback.set(val);
		return this;
	}

	public jnr.ffi.Pointer getUserdata () {
		return userdata.get();
	}

	public WGPUBufferHostMappedPointer setUserdata (jnr.ffi.Pointer val) {
		this.userdata.set(val);
		return this;
	}

}
