
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPUSurfaceGetCurrentTextureStatus {
	Success, Timeout, Outdated, Lost, OutOfMemory, DeviceLost, Error,
}
