
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.CStrPointer;
import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.RustCString;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSwapChainDescriptor extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
	private final @Nullable @CStrPointer Struct.Pointer label = new Pointer();
	private final Unsigned32 usage = new Unsigned32();
	private final Enum<WGPUTextureFormat> format = new Enum<>(WGPUTextureFormat.class);
	private final Unsigned32 width = new Unsigned32();
	private final Unsigned32 height = new Unsigned32();
	private final Enum<WGPUPresentMode> presentMode = new Enum<>(WGPUPresentMode.class);

	private WGPUSwapChainDescriptor () {
	}

	@Deprecated
	public WGPUSwapChainDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUSwapChainDescriptor createHeap () {
		return new WGPUSwapChainDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUSwapChainDescriptor createDirect () {
		WGPUSwapChainDescriptor struct = new WGPUSwapChainDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStruct> getNextInChain () {
		return nextInChain;
	}

	public WGPUSwapChainDescriptor setNextInChain (WGPUChainedStruct... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public java.lang.String getLabel () {
		return RustCString.fromPointer(label.get());
	}

	public WGPUSwapChainDescriptor setLabel (java.lang.String str) {
		this.label.set(RustCString.toPointer(str));
		return this;
	}

	public long getUsage () {
		return usage.get();
	}

	public WGPUSwapChainDescriptor setUsage (long val) {
		this.usage.set(val);
		return this;
	}

	public WGPUTextureFormat getFormat () {
		return format.get();
	}

	public WGPUSwapChainDescriptor setFormat (WGPUTextureFormat val) {
		this.format.set(val);
		return this;
	}

	public long getWidth () {
		return width.get();
	}

	public WGPUSwapChainDescriptor setWidth (long val) {
		this.width.set(val);
		return this;
	}

	public long getHeight () {
		return height.get();
	}

	public WGPUSwapChainDescriptor setHeight (long val) {
		this.height.set(val);
		return this;
	}

	public WGPUPresentMode getPresentMode () {
		return presentMode.get();
	}

	public WGPUSwapChainDescriptor setPresentMode (WGPUPresentMode val) {
		this.presentMode.set(val);
		return this;
	}

}
