
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDawnWireWGSLControl extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final Unsigned32 enableExperimental = new Unsigned32();
	private final Unsigned32 enableUnsafe = new Unsigned32();
	private final Unsigned32 enableTesting = new Unsigned32();

	private WGPUDawnWireWGSLControl () {
	}

	@Deprecated
	public WGPUDawnWireWGSLControl (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUDawnWireWGSLControl createHeap () {
		return new WGPUDawnWireWGSLControl();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUDawnWireWGSLControl createDirect () {
		WGPUDawnWireWGSLControl struct = new WGPUDawnWireWGSLControl();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public long getEnableExperimental () {
		return enableExperimental.get();
	}

	public WGPUDawnWireWGSLControl setEnableExperimental (long val) {
		this.enableExperimental.set(val);
		return this;
	}

	public long getEnableUnsafe () {
		return enableUnsafe.get();
	}

	public WGPUDawnWireWGSLControl setEnableUnsafe (long val) {
		this.enableUnsafe.set(val);
		return this;
	}

	public long getEnableTesting () {
		return enableTesting.get();
	}

	public WGPUDawnWireWGSLControl setEnableTesting (long val) {
		this.enableTesting.set(val);
		return this;
	}

}
