
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDepthStencilState extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
	private final Enum<WGPUTextureFormat> format = new Enum<>(WGPUTextureFormat.class);
	private final Unsigned32 depthWriteEnabled = new Unsigned32();
	private final Enum<WGPUCompareFunction> depthCompare = new Enum<>(WGPUCompareFunction.class);
	private final WGPUStencilFaceState stencilFront = inner(WGPUStencilFaceState.createHeap());
	private final WGPUStencilFaceState stencilBack = inner(WGPUStencilFaceState.createHeap());
	private final Unsigned32 stencilReadMask = new Unsigned32();
	private final Unsigned32 stencilWriteMask = new Unsigned32();
	private final Signed32 depthBias = new Signed32();
	private final Float depthBiasSlopeScale = new Float();
	private final Float depthBiasClamp = new Float();

	private WGPUDepthStencilState () {
	}

	@Deprecated
	public WGPUDepthStencilState (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUDepthStencilState createHeap () {
		return new WGPUDepthStencilState();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUDepthStencilState createDirect () {
		WGPUDepthStencilState struct = new WGPUDepthStencilState();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStruct> getNextInChain () {
		return nextInChain;
	}

	public WGPUDepthStencilState setNextInChain (WGPUChainedStruct... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public WGPUTextureFormat getFormat () {
		return format.get();
	}

	public WGPUDepthStencilState setFormat (WGPUTextureFormat val) {
		this.format.set(val);
		return this;
	}

	public long getDepthWriteEnabled () {
		return depthWriteEnabled.get();
	}

	public WGPUDepthStencilState setDepthWriteEnabled (long val) {
		this.depthWriteEnabled.set(val);
		return this;
	}

	public WGPUCompareFunction getDepthCompare () {
		return depthCompare.get();
	}

	public WGPUDepthStencilState setDepthCompare (WGPUCompareFunction val) {
		this.depthCompare.set(val);
		return this;
	}

	public WGPUStencilFaceState getStencilFront () {
		return stencilFront;
	}

	public WGPUStencilFaceState getStencilBack () {
		return stencilBack;
	}

	public long getStencilReadMask () {
		return stencilReadMask.get();
	}

	public WGPUDepthStencilState setStencilReadMask (long val) {
		this.stencilReadMask.set(val);
		return this;
	}

	public long getStencilWriteMask () {
		return stencilWriteMask.get();
	}

	public WGPUDepthStencilState setStencilWriteMask (long val) {
		this.stencilWriteMask.set(val);
		return this;
	}

	public int getDepthBias () {
		return depthBias.get();
	}

	public WGPUDepthStencilState setDepthBias (int val) {
		this.depthBias.set(val);
		return this;
	}

	public float getDepthBiasSlopeScale () {
		return depthBiasSlopeScale.get();
	}

	public WGPUDepthStencilState setDepthBiasSlopeScale (float val) {
		this.depthBiasSlopeScale.set(val);
		return this;
	}

	public float getDepthBiasClamp () {
		return depthBiasClamp.get();
	}

	public WGPUDepthStencilState setDepthBiasClamp (float val) {
		this.depthBiasClamp.set(val);
		return this;
	}

}
