
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.CStrPointer;
import com.badlogic.gdx.webgpu.utils.RustCString;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDawnCacheDeviceDescriptor extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final @CStrPointer Pointer isolationKey = new Pointer();
	private final Pointer loadDataFunction = new Pointer();
	private final Pointer storeDataFunction = new Pointer();
	private final Pointer functionUserdata = new Pointer();

	private WGPUDawnCacheDeviceDescriptor () {
	}

	@Deprecated
	public WGPUDawnCacheDeviceDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUDawnCacheDeviceDescriptor createHeap () {
		return new WGPUDawnCacheDeviceDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUDawnCacheDeviceDescriptor createDirect () {
		WGPUDawnCacheDeviceDescriptor struct = new WGPUDawnCacheDeviceDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public java.lang.String getIsolationKey () {
		return RustCString.fromPointer(isolationKey.get());
	}

	public WGPUDawnCacheDeviceDescriptor setIsolationKey (java.lang.String str) {
		this.isolationKey.set(RustCString.toPointer(str));
		return this;
	}

	public jnr.ffi.Pointer getLoadDataFunction () {
		return loadDataFunction.get();
	}

	public WGPUDawnCacheDeviceDescriptor setLoadDataFunction (jnr.ffi.Pointer val) {
		this.loadDataFunction.set(val);
		return this;
	}

	public jnr.ffi.Pointer getStoreDataFunction () {
		return storeDataFunction.get();
	}

	public WGPUDawnCacheDeviceDescriptor setStoreDataFunction (jnr.ffi.Pointer val) {
		this.storeDataFunction.set(val);
		return this;
	}

	public jnr.ffi.Pointer getFunctionUserdata () {
		return functionUserdata.get();
	}

	public WGPUDawnCacheDeviceDescriptor setFunctionUserdata (jnr.ffi.Pointer val) {
		this.functionUserdata.set(val);
		return this;
	}

}
