
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSurfaceDescriptorFromWindowsCoreWindow extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final Pointer coreWindow = new Pointer();

	private WGPUSurfaceDescriptorFromWindowsCoreWindow () {
	}

	@Deprecated
	public WGPUSurfaceDescriptorFromWindowsCoreWindow (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUSurfaceDescriptorFromWindowsCoreWindow createHeap () {
		return new WGPUSurfaceDescriptorFromWindowsCoreWindow();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUSurfaceDescriptorFromWindowsCoreWindow createDirect () {
		WGPUSurfaceDescriptorFromWindowsCoreWindow struct = new WGPUSurfaceDescriptorFromWindowsCoreWindow();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public jnr.ffi.Pointer getCoreWindow () {
		return coreWindow.get();
	}

	public WGPUSurfaceDescriptorFromWindowsCoreWindow setCoreWindow (jnr.ffi.Pointer val) {
		this.coreWindow.set(val);
		return this;
	}

}
