
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedFenceDXGISharedHandleExportInfo extends WgpuJavaStruct {

	private final WGPUChainedStructOut chain = inner(WGPUChainedStructOut.createHeap());
	private final Pointer handle = new Pointer();

	private WGPUSharedFenceDXGISharedHandleExportInfo () {
	}

	@Deprecated
	public WGPUSharedFenceDXGISharedHandleExportInfo (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUSharedFenceDXGISharedHandleExportInfo createHeap () {
		return new WGPUSharedFenceDXGISharedHandleExportInfo();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUSharedFenceDXGISharedHandleExportInfo createDirect () {
		WGPUSharedFenceDXGISharedHandleExportInfo struct = new WGPUSharedFenceDXGISharedHandleExportInfo();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStructOut getChain () {
		return chain;
	}

	public jnr.ffi.Pointer getHandle () {
		return handle.get();
	}

	public WGPUSharedFenceDXGISharedHandleExportInfo setHandle (jnr.ffi.Pointer val) {
		this.handle.set(val);
		return this;
	}

}
