
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.CStrPointer;
import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.RustCString;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUTextureViewDescriptor extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
	private final @Nullable @CStrPointer Struct.Pointer label = new Pointer();
	private final Enum<WGPUTextureFormat> format = new Enum<>(WGPUTextureFormat.class);
	private final Enum<WGPUTextureViewDimension> dimension = new Enum<>(WGPUTextureViewDimension.class);
	private final Unsigned32 baseMipLevel = new Unsigned32();
	private final Unsigned32 mipLevelCount = new Unsigned32();
	private final Unsigned32 baseArrayLayer = new Unsigned32();
	private final Unsigned32 arrayLayerCount = new Unsigned32();
	private final Enum<WGPUTextureAspect> aspect = new Enum<>(WGPUTextureAspect.class);

	private WGPUTextureViewDescriptor () {
	}

	@Deprecated
	public WGPUTextureViewDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUTextureViewDescriptor createHeap () {
		return new WGPUTextureViewDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUTextureViewDescriptor createDirect () {
		WGPUTextureViewDescriptor struct = new WGPUTextureViewDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStruct> getNextInChain () {
		return nextInChain;
	}

	public WGPUTextureViewDescriptor setNextInChain (WGPUChainedStruct... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public java.lang.String getLabel () {
		return RustCString.fromPointer(label.get());
	}

	public WGPUTextureViewDescriptor setLabel (java.lang.String str) {
		this.label.set(RustCString.toPointer(str));
		return this;
	}

	public WGPUTextureFormat getFormat () {
		return format.get();
	}

	public WGPUTextureViewDescriptor setFormat (WGPUTextureFormat val) {
		this.format.set(val);
		return this;
	}

	public WGPUTextureViewDimension getDimension () {
		return dimension.get();
	}

	public WGPUTextureViewDescriptor setDimension (WGPUTextureViewDimension val) {
		this.dimension.set(val);
		return this;
	}

	public long getBaseMipLevel () {
		return baseMipLevel.get();
	}

	public WGPUTextureViewDescriptor setBaseMipLevel (long val) {
		this.baseMipLevel.set(val);
		return this;
	}

	public long getMipLevelCount () {
		return mipLevelCount.get();
	}

	public WGPUTextureViewDescriptor setMipLevelCount (long val) {
		this.mipLevelCount.set(val);
		return this;
	}

	public long getBaseArrayLayer () {
		return baseArrayLayer.get();
	}

	public WGPUTextureViewDescriptor setBaseArrayLayer (long val) {
		this.baseArrayLayer.set(val);
		return this;
	}

	public long getArrayLayerCount () {
		return arrayLayerCount.get();
	}

	public WGPUTextureViewDescriptor setArrayLayerCount (long val) {
		this.arrayLayerCount.set(val);
		return this;
	}

	public WGPUTextureAspect getAspect () {
		return aspect.get();
	}

	public WGPUTextureViewDescriptor setAspect (WGPUTextureAspect val) {
		this.aspect.set(val);
		return this;
	}

}
