
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUComputePassTimestampWrites extends WgpuJavaStruct {

	private final Pointer querySet = new Pointer();
	private final Unsigned32 beginningOfPassWriteIndex = new Unsigned32();
	private final Unsigned32 endOfPassWriteIndex = new Unsigned32();

	private WGPUComputePassTimestampWrites () {
	}

	@Deprecated
	public WGPUComputePassTimestampWrites (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUComputePassTimestampWrites createHeap () {
		return new WGPUComputePassTimestampWrites();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUComputePassTimestampWrites createDirect () {
		WGPUComputePassTimestampWrites struct = new WGPUComputePassTimestampWrites();
		struct.useDirectMemory();
		return struct;
	}

	public jnr.ffi.Pointer getQuerySet () {
		return querySet.get();
	}

	public WGPUComputePassTimestampWrites setQuerySet (jnr.ffi.Pointer val) {
		this.querySet.set(val);
		return this;
	}

	public long getBeginningOfPassWriteIndex () {
		return beginningOfPassWriteIndex.get();
	}

	public WGPUComputePassTimestampWrites setBeginningOfPassWriteIndex (long val) {
		this.beginningOfPassWriteIndex.set(val);
		return this;
	}

	public long getEndOfPassWriteIndex () {
		return endOfPassWriteIndex.get();
	}

	public WGPUComputePassTimestampWrites setEndOfPassWriteIndex (long val) {
		this.endOfPassWriteIndex.set(val);
		return this;
	}

}
