
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPUPrimitiveTopology {
	Undefined, PointList, LineList, LineStrip, TriangleList, TriangleStrip,
}
