
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUColorWriteMask {
	public static final int None = 0x0;
	public static final int Red = 0x1;
	public static final int Green = 0x2;
	public static final int Blue = 0x4;
	public static final int Alpha = 0x8;
	public static final int All = 0xf;
}
