
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSurfaceDescriptorFromMetalLayer extends WgpuJavaStruct {

	private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
	private final Pointer layer = new Pointer();

	private WGPUSurfaceDescriptorFromMetalLayer () {
	}

	@Deprecated
	public WGPUSurfaceDescriptorFromMetalLayer (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUSurfaceDescriptorFromMetalLayer createHeap () {
		return new WGPUSurfaceDescriptorFromMetalLayer();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUSurfaceDescriptorFromMetalLayer createDirect () {
		WGPUSurfaceDescriptorFromMetalLayer struct = new WGPUSurfaceDescriptorFromMetalLayer();
		struct.useDirectMemory();
		return struct;
	}

	public WGPUChainedStruct getChain () {
		return chain;
	}

	public jnr.ffi.Pointer getLayer () {
		return layer.get();
	}

	public WGPUSurfaceDescriptorFromMetalLayer setLayer (jnr.ffi.Pointer val) {
		this.layer.set(val);
		return this;
	}

}
