
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedTextureMemoryBeginAccessDescriptor extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
	private final Unsigned32 concurrentRead = new Unsigned32();
	private final Unsigned32 initialized = new Unsigned32();
	private final size_t fenceCount = new size_t();
	private final Pointer fences = new Pointer();
	private final Pointer signaledValues = new Pointer();

	private WGPUSharedTextureMemoryBeginAccessDescriptor () {
	}

	@Deprecated
	public WGPUSharedTextureMemoryBeginAccessDescriptor (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUSharedTextureMemoryBeginAccessDescriptor createHeap () {
		return new WGPUSharedTextureMemoryBeginAccessDescriptor();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUSharedTextureMemoryBeginAccessDescriptor createDirect () {
		WGPUSharedTextureMemoryBeginAccessDescriptor struct = new WGPUSharedTextureMemoryBeginAccessDescriptor();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStruct> getNextInChain () {
		return nextInChain;
	}

	public WGPUSharedTextureMemoryBeginAccessDescriptor setNextInChain (WGPUChainedStruct... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public long getConcurrentRead () {
		return concurrentRead.get();
	}

	public WGPUSharedTextureMemoryBeginAccessDescriptor setConcurrentRead (long val) {
		this.concurrentRead.set(val);
		return this;
	}

	public long getInitialized () {
		return initialized.get();
	}

	public WGPUSharedTextureMemoryBeginAccessDescriptor setInitialized (long val) {
		this.initialized.set(val);
		return this;
	}

	public long getFenceCount () {
		return fenceCount.get();
	}

	public WGPUSharedTextureMemoryBeginAccessDescriptor setFenceCount (long val) {
		this.fenceCount.set(val);
		return this;
	}

	public jnr.ffi.Pointer getFences () {
		return fences.get();
	}

	public WGPUSharedTextureMemoryBeginAccessDescriptor setFences (jnr.ffi.Pointer val) {
		this.fences.set(val);
		return this;
	}

	public jnr.ffi.Pointer getSignaledValues () {
		return signaledValues.get();
	}

	public WGPUSharedTextureMemoryBeginAccessDescriptor setSignaledValues (jnr.ffi.Pointer val) {
		this.signaledValues.set(val);
		return this;
	}

}
