
package com.badlogic.gdx.webgpu.webgpu;

import com.badlogic.gdx.webgpu.utils.JavaWebGPU;
import com.badlogic.gdx.webgpu.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUBufferMapCallbackInfo extends WgpuJavaStruct {

	private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
	private final Enum<WGPUCallbackMode> mode = new Enum<>(WGPUCallbackMode.class);
	private final Pointer callback = new Pointer();
	private final Pointer userdata = new Pointer();

	private WGPUBufferMapCallbackInfo () {
	}

	@Deprecated
	public WGPUBufferMapCallbackInfo (Runtime runtime) {
		super(runtime);
	}

	/** Creates this struct on the java heap. In general, this should <b>not</b> be used because these structs cannot be directly
	 * passed into native code. */
	public static WGPUBufferMapCallbackInfo createHeap () {
		return new WGPUBufferMapCallbackInfo();
	}

	/** Creates this struct in direct memory. This is how most structs should be created (unless, they are members of a nothing
	 * struct)
	 * 
	 * @see WgpuJavaStruct#useDirectMemory */
	public static WGPUBufferMapCallbackInfo createDirect () {
		WGPUBufferMapCallbackInfo struct = new WGPUBufferMapCallbackInfo();
		struct.useDirectMemory();
		return struct;
	}

	public DynamicStructRef<WGPUChainedStruct> getNextInChain () {
		return nextInChain;
	}

	public WGPUBufferMapCallbackInfo setNextInChain (WGPUChainedStruct... x) {
		if (x.length == 0 || x[0] == null) {
			this.nextInChain.set(JavaWebGPU.createNullPointer());
		} else {
			this.nextInChain.set(x);
		}
		return this;
	}

	public WGPUCallbackMode getMode () {
		return mode.get();
	}

	public WGPUBufferMapCallbackInfo setMode (WGPUCallbackMode val) {
		this.mode.set(val);
		return this;
	}

	public jnr.ffi.Pointer getCallback () {
		return callback.get();
	}

	public WGPUBufferMapCallbackInfo setCallback (jnr.ffi.Pointer val) {
		this.callback.set(val);
		return this;
	}

	public jnr.ffi.Pointer getUserdata () {
		return userdata.get();
	}

	public WGPUBufferMapCallbackInfo setUserdata (jnr.ffi.Pointer val) {
		this.userdata.set(val);
		return this;
	}

}
