
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
import jnr.ffi.Pointer;
import jnr.ffi.annotations.Delegate;

public interface WGPUBufferMapCallback2 {

	@Delegate
	void invoke (WGPUMapAsyncStatus status, String message, Pointer userdata1, Pointer userdata2);
}
