
package com.badlogic.gdx.webgpu.webgpu;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUTextureUsage {
	public static final int None = 0x0;
	public static final int CopySrc = 0x1;
	public static final int CopyDst = 0x2;
	public static final int TextureBinding = 0x4;
	public static final int StorageBinding = 0x8;
	public static final int RenderAttachment = 0x10;
	public static final int TransientAttachment = 0x20;
	public static final int StorageAttachment = 0x40;
}
